GuLiEdu/urls.py
from django.conf import settings
from django.urls import path, include, re_path
from django.views.static import serve
from extra_apps import xadmin
from users.views import IndexView
import users.views as view

urlpatterns = [
    path('admin/', xadmin.site.urls),
    path('captcha/', include('captcha.urls')),
    path('ueditor/', include('DjangoUeditor.urls')),
    path('users/', include(('users.urls', 'users'), namespace='users')),
    path('course/', include(('courses.urls', 'courses'), namespace='courses')),
    path('orgs/', include(('orgs.urls', 'orgs'), namespace='orgs')),
    path('operations/', include(('operations.urls', 'operations'), namespace='operations')),
    path('', IndexView.as_view()),
    re_path(r'^media/(?P<path>.*)', serve, {"document_root": settings.MEDIA_ROOT}),
]
# handler404 = 'users.views.page_not_found_error'
handler500 = 'users.views.page_error'

apps/courses/urls.py
from django.conf.urls import url
from django.urls import path
from .views import course_list, course_detail, course_video, course_comment


urlpatterns = [
    path('course_list/', course_list, name='course_list'),
    url(r'^course_detail/(\d+)/$', course_detail, name='course_detail'),
    url(r'^course_video/(\d+)/$', course_video, name='course_video'),
    url(r'^course_comment/(\d+)/$', course_comment, name='course_comment'),
]

apps/operations/urls.py
from django.urls import path
from .views import user_ask, user_love, user_comment, user_delete_love


urlpatterns = [
    path('user_ask/', user_ask, name='user_ask'),
    path('user_love/', user_love, name='user_love'),
    path('user_comment/', user_comment, name='user_comment'),
    path('user_delete_love/', user_delete_love, name='user_delete_love'),
]

apps/orgs/urls.py
from django.conf.urls import url
from django.urls import path

from orgs.views import org_list, org_detail, org_detail_course, org_detail_desc, org_detail_teachers, teacher_list,\
    teacher_detail

urlpatterns = [
    path('org_list/', org_list, name='org_list'),
    url(r'^org_detail/(\d+)/$', org_detail, name='org_detail'),
    url(r'^org_detail_course/(\d+)/$', org_detail_course, name='org_detail_course'),
    url(r'^org_detail_desc/(\d+)/$', org_detail_desc, name='org_detail_desc'),
    url(r'^org_detail_teachers/(\d+)/$', org_detail_teachers, name='org_detail_teachers'),
    url(r'^teacher_detail/(\d+)/$', teacher_detail, name='teacher_detail'),
    path('teacher_list/', teacher_list, name='teacher_list')
]

extra_apps/DjangoUeditor/urls.py
# -*- coding: utf-8 -*-
import django
from .views import get_ueditor_controller

DJANGO_VERSION = django.VERSION[:2]


if DJANGO_VERSION >= (1, 8):
    from django.conf.urls import url
    urlpatterns = [
        url(r'^controller/$', get_ueditor_controller)
    ]

else:
    try:
        from django.conf.urls import patterns, url
    except ImportError:
        from django.conf.urls.defaults import patterns, url

    urlpatterns = patterns('',
        url(r'^controller/$', get_ueditor_controller)
    )

apps/courses/models.py
from datetime import datetime

from django.db import models

from DjangoUeditor.models import UEditorField
from orgs.models import TeacherInfo, OrgInfo


# Create your models here.


class CourseInfo(models.Model):
    image = models.ImageField(upload_to='course/', max_length=200, verbose_name='课程封面')
    name = models.CharField(max_length=20, verbose_name='课程名')
    study_time = models.IntegerField(default=0, verbose_name='学习时长')
    study_num = models.IntegerField(default=0, verbose_name='学习人数')
    level = models.CharField(choices=(('gj', '高级'), ('zj', '中级'), ('cj', '初级')),
                             verbose_name='课程难度', max_length=5, default='cj')
    love_num = models.IntegerField(default=0, verbose_name='收藏数')
    click_num = models.IntegerField(default=0, verbose_name='访问数')
    desc = models.TextField(verbose_name='课程简介')
    detail = UEditorField(verbose_name='课程详情',
                          width=700,
                          height=400,
                          toolbars='full',
                          imagePath='ueditor/images/',
                          filePath='ueditor/files/',
                          upload_settings={'imageMaxSizing': 1024000},
                          default='')
    category = models.CharField(choices=(('qd', '前端开发'), ('hd', '后端开发')),
                                verbose_name='课程类型', max_length=5)
    course_notice = models.CharField(max_length=50, verbose_name='课程公告',
                                     null=True, blank=True)
    course_need = models.CharField(max_length=100, verbose_name='课程须知',
                                   null=True, blank=True)
    teacher_tell = models.CharField(max_length=100, verbose_name='讲师提醒',
                                    null=True, blank=True)
    org_info = models.ForeignKey(OrgInfo, verbose_name='所属机构',
                                 on_delete=models.CASCADE)
    teacher_Info = models.ForeignKey(TeacherInfo, verbose_name='讲师',
                                     on_delete=models.CASCADE)
    is_banner = models.BooleanField(default=False,
                                    verbose_name='是否轮播')
    add_time = models.DateTimeField(default=datetime.now, verbose_name='添加时间')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural = verbose_name = '课程信息'


class LessonInfo(models.Model):
    name = models.CharField(max_length=50, verbose_name='章节名')
    course_info = models.ForeignKey(CourseInfo, verbose_name='所属课程',
                                    on_delete=models.CASCADE)
    add_time = models.DateTimeField(default=datetime.now, verbose_name='添加时间')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural = verbose_name = '章节信息'


class VideoInfo(models.Model):
    name = models.CharField(max_length=50, verbose_name='视频名称')
    study_time = models.IntegerField(default=0, verbose_name='视频时长')
    url = models.URLField(default='http://www.atguigu.com', verbose_name='视频链接', max_length=200)
    add_time = models.DateTimeField(default=datetime.now, verbose_name='添加时间')
    lesson_info = models.ForeignKey(LessonInfo, verbose_name='所属章节',
                                    on_delete=models.CASCADE)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural = verbose_name = '视频信息'


class SourceInfo(models.Model):
    name = models.CharField(max_length=50, verbose_name='资源名称')
    download = models.FileField(upload_to='source/', verbose_name='资源链接', max_length=200)
    course_info = models.ForeignKey(CourseInfo, verbose_name='所属课程',
                                    on_delete=models.CASCADE)
    add_time = models.DateTimeField(default=datetime.now, verbose_name='添加时间')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural = verbose_name = '资源信息'

apps/operations/models.py
from datetime import datetime

from django.db import models

from courses.models import CourseInfo
from users.models import UserProfile
# Create your models here.


class UserAsk(models.Model):
    name = models.CharField(max_length=30, verbose_name='姓名')
    phone = models.CharField(max_length=11, verbose_name='手机')
    course = models.CharField(max_length=20, verbose_name='课程')
    add_time = models.DateTimeField(default=datetime.now, verbose_name='添加时间')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural = verbose_name = '咨询信息'


class UserLove(models.Model):
    love_man = models.ForeignKey(UserProfile, verbose_name='收藏人',
                                 on_delete=models.CASCADE)
    love_id = models.IntegerField(verbose_name='收藏id')
    love_type = models.IntegerField(choices=((1, 'org'), (2, 'course'), (3, 'teacher')),
                                    verbose_name='收藏类别')
    love_status = models.BooleanField(default=False, verbose_name='收藏状态')
    add_time = models.DateTimeField(default=datetime.now, verbose_name='收藏时间')

    def __str__(self):
        return self.love_man.username

    class Meta:
        verbose_name_plural = verbose_name = '收藏信息'


class UserCourse(models.Model):
    study_man = models.ForeignKey(UserProfile, verbose_name='学习用户',
                                  on_delete=models.CASCADE)
    study_course = models.ForeignKey(CourseInfo, verbose_name='学习课程',
                                     on_delete=models.CASCADE)
    add_time = models.DateTimeField(default=datetime.now, verbose_name='学习时间')

    def __str__(self):
        return self.study_man.username

    class Meta:
        unique_together = ('study_man', 'study_course')
        verbose_name_plural = verbose_name = '用户学习课程信息'


class UserComment(models.Model):
    comment_man = models.ForeignKey(UserProfile, verbose_name='评论用户',
                                    on_delete=models.CASCADE)
    comment_course = models.ForeignKey(CourseInfo, verbose_name='评论课程',
                                       on_delete=models.CASCADE)
    comment_content = models.TextField(verbose_name='评论内容')
    add_time = models.DateTimeField(default=datetime.now, verbose_name='评论时间')

    def __str__(self):
        return self.comment_content

    class Meta:
        verbose_name_plural = verbose_name = '用户评论信息'


class UserMessage(models.Model):
    message_man = models.IntegerField(default=0, verbose_name='消息用户')
    message_content = models.TextField(verbose_name='消息内容')
    message_status = models.BooleanField(default=False, verbose_name='消息状态')
    add_time = models.DateTimeField(default=datetime.now, verbose_name='发送时间')

    def __str__(self):
        return self.message_content

    class Meta:
        verbose_name_plural = verbose_name = '用户消息'

apps/orgs/models.py
from datetime import datetime

from django.db import models

# Create your models here.
from DjangoUeditor.models import UEditorField


class CityInfo(models.Model):
    name = models.CharField(max_length=50, verbose_name='城市名')
    add_time = models.DateTimeField(default=datetime.now, verbose_name='添加时间')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural = verbose_name = '城市信息'


class OrgInfo(models.Model):
    image = models.ImageField(upload_to='org/', max_length=200, verbose_name='机构图片')
    name = models.CharField(max_length=20, verbose_name='机构名称')
    course_num = models.IntegerField(default=0, verbose_name='课程数')
    study_num = models.IntegerField(default=0, verbose_name='学习人数')
    address = models.CharField(max_length=200, verbose_name='机构地址')
    desc = models.TextField(verbose_name='机构简介')
    detail = UEditorField(verbose_name='机构详情',
                          width=700,
                          height=400,
                          toolbars='full',
                          imagePath='ueditor/images/',
                          filePath='ueditor/files/',
                          upload_settings={'imageMaxSizing': 1024000},
                          default='')
    love_num = models.IntegerField(default=0, verbose_name='收藏数')
    click_num = models.IntegerField(default=0, verbose_name='访问数')
    category = models.CharField(choices=(('pxjg', '培训机构'), ('gx', '高校'), ('gr', '个人')),
                                verbose_name='机构类别', max_length=10)
    add_time = models.DateTimeField(default=datetime.now, verbose_name='添加时间')
    city_info = models.ForeignKey(CityInfo, verbose_name='所属城市',
                                  on_delete=models.CASCADE)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural = verbose_name = '机构信息'


class TeacherInfo(models.Model):
    image = models.ImageField(upload_to='teacher/', max_length=200, verbose_name='讲师头像')
    name = models.CharField(max_length=20, verbose_name='讲师姓名')
    work_year = models.IntegerField(default=3, verbose_name='工作年限')
    work_position = models.CharField(max_length=50, verbose_name='工作职位')
    work_style = models.CharField(max_length=20, verbose_name='教学特点')
    work_company = models.ForeignKey(OrgInfo, verbose_name='所属机构',
                                     on_delete=models.CASCADE)
    age = models.IntegerField(default=28, verbose_name='讲师年龄')
    gender = models.CharField(choices=(('girl', '女'), ('boy', '男')), max_length=10, verbose_name='性别',
                              default='girl')
    love_num = models.IntegerField(default=0, verbose_name='收藏数')
    click_num = models.IntegerField(default=0, verbose_name='访问数')
    add_time = models.DateTimeField(default=datetime.now, verbose_name='添加时间')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural = verbose_name = '讲师信息'

apps/courses/views.py
from django.db.models import Q
from django.shortcuts import render
from django.core.paginator import Paginator
# Create your views here.
from courses.models import CourseInfo
from operations.models import UserLove, UserCourse
from django.contrib.auth.decorators import login_required
from utils.decorators import login_decorator

def course_list(request):
    sort = request.GET.get('sort', '')

    all_courses = CourseInfo.objects.all()
    recommend_courses = all_courses.order_by('-add_time')[:3]
    # 全局搜索
    keyword = request.GET.get('keyword', '')
    if keyword:
        all_courses = all_courses.filter(Q(name__icontains=keyword)
                                         | Q(desc__icontains=keyword)
                                         | Q(detail__icontains=keyword))

    if sort:
        all_courses = all_courses.order_by('-' + sort)
    page = request.GET.get('page', 1)
    pages = Paginator(all_courses, 6)
    try:
        pager = pages.page(page)
    except:
        pager = pages.page(1)

    return render(request, 'courses/course-list.html', locals())


def course_detail(request, course_id):
    if course_id:
        course = CourseInfo.objects.filter(id=int(course_id))[0]
        course.click_num += 1
        course.save()
        related_course = CourseInfo.objects.filter(category=course.category).exclude(id=int(course_id))[:2]
        love_course = False
        love_org = False
        if request.user.is_authenticated:
            lovecourse = UserLove.objects.filter(love_id=int(course_id),
                                                 love_type=2,
                                                 love_status=True,
                                                 love_man=request.user)
            if lovecourse:
                love_course = True
            loveorg = UserLove.objects.filter(love_id=course.org_info.id, love_type=1,
                                              love_status=True,
                                              love_man=request.user)
            if loveorg:
                love_org = True
        return render(request, 'courses/course-detail.html', locals())


def course_study_list(course_id):
    course = CourseInfo.objects.filter(id=int(course_id)).first()
    # 学过该课的同学还学过
    users = UserCourse.objects.filter(study_course=course).all()
    user_list = [user.study_man for user in users]
    user_course_list = UserCourse.objects.filter(study_man__in=user_list).exclude(study_course=course).all()
    courses_list = list(set([user.study_course for user in user_course_list]))[:3]
    return courses_list

@login_decorator
def course_video(request, course_id):
    if course_id:
        course = CourseInfo.objects.filter(id=int(course_id)).first()

        user_course = UserCourse.objects.filter(study_man=request.user, study_course=course)
        if not user_course:
            a = UserCourse()
            a.study_man = request.user
            a.study_course = course
            a.save()
            course.study_num += 1
            course.save()
            # 用户所学的课程
            user_course_list = UserCourse.objects.filter(study_man=request.user).all()
            user_course = [user_course.study_course for user_course in user_course_list]
            # 找出这些课程所对应的机构
            org_list = list(set([course.org_info for course in user_course]))
            # 如果新学习的课程机构不在学生所学习过的机构列表中，则该机构的学习人数+1
            if course.org_info not in org_list:
                course.org_info.study_num += 1
                course.org_info.save()

        # 学过该课的同学还学过
        courses_list = course_study_list(course_id)

        return render(request, 'courses/course-video.html', locals())


def course_comment(request, course_id):
    if course_id:
        course = CourseInfo.objects.filter(id=int(course_id)).first()
        comment_list = course.usercomment_set.all()
        courses_list = course_study_list(course_id)
        return render(request, 'courses/course-comment.html', locals())

templates/courses/course-comment.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %}
    公开课评论 - 谷粒教育网
{% endblock %}
{% block css %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/guli/course/learn-less.css ' %}"/>
    <link rel="stylesheet" type="text/css" href="{% static 'css/guli/course/course-comment.css' %}"/>
    <link rel="stylesheet" type="text/css" href="{% static 'css/guli/base.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/guli/common-less.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/guli/course/common-less.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/mooc.css' %}"/>
{% endblock %}
{% block content %}
    <section>
        <div class="wp">
            <div class="crumbs">
                <ul>
                    <li><a href="/">首页</a>></li>
                    <li><a href="/course/course_list/">公开课程</a>></li>
                    <li><a href="{% url 'courses:course_detail' course.id %}">课程详情</a>></li>
                    <li>课程评论</li>
                </ul>
            </div>
        </div>
    </section>


    <div id="main">
        <div class="course-infos">
            <div class="w pr">
                <div style="height: 15px" class="path">
                </div>
                <div class="hd">
                    <h2 class="l">{{ course.name }}</h2>
                </div>
                <div class="statics clearfix">
                    <div class="static-item ">
                        <span class="meta-value">
                            <strong>
                                {% if course.level == 'gj' %}高级
                                {% elif course.level == 'zj' %}中级
                                {% else %}初级
                                {% endif %}
                            </strong>
                        </span>
                        <span class="meta">难度</span>
                        <em></em>
                    </div>
                    <div class="static-item static-time">
                        <span class="meta-value">{{ course.study_time }}分钟</span>
                        <span class="meta">时长</span>
                        <em></em>
                    </div>
                    <div class="static-item">
                        <span class="meta-value"><strong>{{ course.study_num }}</strong></span>
                        <span class="meta">学习人数</span>
                        <em></em>
                    </div>
                </div>
            </div>
        </div>
        <div class="course-info-main clearfix w has-progress">

            <div class="info-bar clearfix">
                <div class="content-wrap clearfix">
                    <div class="content">
                        <div class="mod-tab-menu">
                            <ul class="course-menu clearfix">
                                <li><a class="ui-tabs-active " id="learnOn"
                                       href="{% url 'courses:course_video' course.id %}"><span>章节</span></a>
                                </li>
                                <li><a id="commentOn" class="active"
                                       href="{% url 'courses:course_comment' course.id %}"><span>评论</span></a></li>
                            </ul>
                        </div>

                        <!--发布评论-->
                        <div id="js-pub-container" class="issques clearfix js-form">
                            <div class="wgt-ipt-wrap pub-editor-wrap " id="js-pl-input-fake">
                                <textarea id="js-pl-textarea" class="" placeholder="扯淡、吐槽、表扬、鼓励……想说啥就说啥！"></textarea>
                            </div>
                            <input type="button" id="js-pl-submit" class="pub-btn" data-cid="452" value="发表评论">
                            <p class="global-errortip js-global-error"></p>
                        </div>
                        <div id="course_note">
                            <ul class="mod-post" id="comment-list">
                                {% for comment in comment_list %}
                                <li class="post-row">
                                    <div class="media">
                                        <span target="_blank"><img src='/media/{{ comment.comment_man.image }}' width='40'
                                                                   height='40'/></span>
                                    </div>
                                    <div class="bd">
                                        <div class="tit">
                                            <span target="_blank">{{ comment.comment_man.nick_name }}</span>
                                        </div>
                                        <p class="cnt">{{ comment.comment_content}}</p>
                                        <div class="footer clearfix">
                                            <span title="创建时间" class="l timeago">时间：{{ comment.add_time }}</span>
                                        </div>
                                    </div>
                                </li>
                                {% endfor %}


                            </ul>
                        </div>

                    </div>
                    <div class="aside r">
                        <div class="bd">

                            <div class="box mb40">
                                <h4>资料下载</h4>
                                <ul class="downlist">
                                    {% for source in course.sourceinfo_set.all %}
                                        <li>
                                            <span><i
                                                    class="aui-iconfont aui-icon-file"></i>&nbsp;&nbsp;{{ source.name }}</span>
                                            <a href="/media/{{ source.download }}" class="downcode"
                                               target="_blank" download="" data-id="274" title="">下载</a>
                                        </li>
                                    {% endfor %}
                                </ul>
                            </div>
                            <div class="box mb40">
                                <h4>讲师提示</h4>
                                <div class="teacher-info">
                                    <a href="{% url 'orgs:teacher_detail' course.teacher_Info.id %}" target="_blank">
                                        <img src='/media/{{ course.teacher_Info.image }}' width='80' height='80'/>
                                    </a>
                                    <span class="tit">
          <a href="{% url 'orgs:teacher_detail' course.teacher_Info.id %}" target="_blank">{{ course.teacher_Info.name }}</a>
        </span>
                                    <span class="job">{{ course.teacher_Info.work_position }}</span>
                                </div>
                                <div class="course-info-tip">
                                    <dl class="first">
                                        <dt>课程须知</dt>
                                        <dd class="autowrap">{{ course.course_need }}</dd>
                                    </dl>
                                    <dl>
                                        <dt>老师告诉你能学到什么？</dt>
                                        <dd class="autowrap">{{ course.teacher_tell }}</dd>
                                    </dl>
                                </div>
                            </div>


                            <div class="cp-other-learned  js-comp-tabs">
                                <div class="cp-header clearfix">
                                    <h2 class="cp-tit l">学过该课的同学还学过</h2>
                                </div>
                                <div class="cp-body">
                                    <div class="cp-tab-pannel js-comp-tab-pannel" data-pannel="course"
                                         style="display: block">
                                        <!-- img 200 x 112 -->
                                        <ul class="other-list">
                                            {% for cou in courses_list %}
                                            <li class="curr">
                                                <a href="{% url 'courses:course_detail' cou.id %}" target="_self">
                                                    <img src="/media/{{ cou.image }}">
                                                    <span class="name autowrap">{{ cou.name }}</span>
                                                </a>
                                            </li>
                                            {% endfor %}
                                        </ul>
                                    </div>

                                </div>
                            </div>

                        </div>
                    </div>
                </div>
                <div class="clear"></div>

            </div>

        </div>
    </div>
{% endblock %}
{% block js %}
    <script type="text/javascript">
        //添加评论
        $(function () {
            $("#js-pl-submit").click(function () {
                let comment_course = {{ course.id }};
                let comment_content = $("#js-pl-textarea").val();
                $.ajax({
                    type: "POST",
                    url: "{% url 'operations:user_comment' %}",
                    data: {
                        "comment_course": comment_course,
                        "comment_content": comment_content,
                        "csrfmiddlewaretoken": '{{ csrf_token }}'
                    },
                    success: function (callback) {
                        if (callback.status == 'ok') {
                            window.location.reload()
                        }else{
                            alert(callback.msg)
                        }
                    }
                })
            })
        })
    </script>
{% endblock %}