GuLiEdu/urls.py
from django.conf import settings
from django.urls import path, include, re_path
from django.views.static import serve
from extra_apps import xadmin
from users.views import IndexView
import users.views as view

urlpatterns = [
    path('admin/', xadmin.site.urls),
    path('captcha/', include('captcha.urls')),
    path('ueditor/', include('DjangoUeditor.urls')),
    path('users/', include(('users.urls', 'users'), namespace='users')),
    path('course/', include(('courses.urls', 'courses'), namespace='courses')),
    path('orgs/', include(('orgs.urls', 'orgs'), namespace='orgs')),
    path('operations/', include(('operations.urls', 'operations'), namespace='operations')),
    path('', IndexView.as_view()),
    re_path(r'^media/(?P<path>.*)', serve, {"document_root": settings.MEDIA_ROOT}),
]
# handler404 = 'users.views.page_not_found_error'
handler500 = 'users.views.page_error'

apps/courses/urls.py
from django.conf.urls import url
from django.urls import path
from .views import course_list, course_detail, course_video, course_comment


urlpatterns = [
    path('course_list/', course_list, name='course_list'),
    url(r'^course_detail/(\d+)/$', course_detail, name='course_detail'),
    url(r'^course_video/(\d+)/$', course_video, name='course_video'),
    url(r'^course_comment/(\d+)/$', course_comment, name='course_comment'),
]

apps/operations/urls.py
from django.urls import path
from .views import user_ask, user_love, user_comment, user_delete_love


urlpatterns = [
    path('user_ask/', user_ask, name='user_ask'),
    path('user_love/', user_love, name='user_love'),
    path('user_comment/', user_comment, name='user_comment'),
    path('user_delete_love/', user_delete_love, name='user_delete_love'),
]

apps/orgs/urls.py
from django.conf.urls import url
from django.urls import path

from orgs.views import org_list, org_detail, org_detail_course, org_detail_desc, org_detail_teachers, teacher_list,\
    teacher_detail

urlpatterns = [
    path('org_list/', org_list, name='org_list'),
    url(r'^org_detail/(\d+)/$', org_detail, name='org_detail'),
    url(r'^org_detail_course/(\d+)/$', org_detail_course, name='org_detail_course'),
    url(r'^org_detail_desc/(\d+)/$', org_detail_desc, name='org_detail_desc'),
    url(r'^org_detail_teachers/(\d+)/$', org_detail_teachers, name='org_detail_teachers'),
    url(r'^teacher_detail/(\d+)/$', teacher_detail, name='teacher_detail'),
    path('teacher_list/', teacher_list, name='teacher_list')
]

apps/users/urls.py
from django.conf.urls import url
from django.urls import path

from users.views import RegisterView, LoginView, user_logout, user_active, ForgetView, user_reset, user_info, \
    user_changeimage, user_changeinfo, user_changeemail, user_resetemail, user_course, user_fav_org, user_fav_teacher,\
    user_fav_course, user_message, user_message_read, user_change_pwd

urlpatterns = [
    path('user_register/', RegisterView.as_view(), name='user_register'),
    path('user_login/', LoginView.as_view(), name='user_login'),
    path('user_logout/', user_logout, name='user_logout'),
    url(r'^user_active/(.*)/$', user_active, name='user_active'),
    path('user_forget/', ForgetView.as_view(), name='user_forget'),
    url(r'^user_reset/(.*)/$', user_reset, name='user_reset'),
    path('user_info/', user_info, name='user_info'),
    path('user_changeimage/', user_changeimage, name='user_changeimage'),
    path('user_changeinfo/', user_changeinfo, name='user_changeinfo'),
    path('user_changeemail/', user_changeemail, name='user_changeemail'),
    path('user_resetemail/', user_resetemail, name='user_resetemail'),
    path('user_course/', user_course, name='user_course'),
    path('user_fav_org/', user_fav_org, name='user_fav_org'),
    path('user_fav_course/', user_fav_course, name='user_fav_course'),
    path('user_fav_teacher/', user_fav_teacher, name='user_fav_teacher'),
    path('user_message/', user_message, name='user_message'),
    path('user_message_read/', user_message_read, name='user_message_read'),
    path('user_change_pwd/', user_change_pwd, name='user_change_pwd'),

]

extra_apps/DjangoUeditor/urls.py
# -*- coding: utf-8 -*-
import django
from .views import get_ueditor_controller

DJANGO_VERSION = django.VERSION[:2]


if DJANGO_VERSION >= (1, 8):
    from django.conf.urls import url
    urlpatterns = [
        url(r'^controller/$', get_ueditor_controller)
    ]

else:
    try:
        from django.conf.urls import patterns, url
    except ImportError:
        from django.conf.urls.defaults import patterns, url

    urlpatterns = patterns('',
        url(r'^controller/$', get_ueditor_controller)
    )

apps/courses/models.py
from datetime import datetime

from django.db import models

from DjangoUeditor.models import UEditorField
from orgs.models import TeacherInfo, OrgInfo


# Create your models here.


class CourseInfo(models.Model):
    image = models.ImageField(upload_to='course/', max_length=200, verbose_name='课程封面')
    name = models.CharField(max_length=20, verbose_name='课程名')
    study_time = models.IntegerField(default=0, verbose_name='学习时长')
    study_num = models.IntegerField(default=0, verbose_name='学习人数')
    level = models.CharField(choices=(('gj', '高级'), ('zj', '中级'), ('cj', '初级')),
                             verbose_name='课程难度', max_length=5, default='cj')
    love_num = models.IntegerField(default=0, verbose_name='收藏数')
    click_num = models.IntegerField(default=0, verbose_name='访问数')
    desc = models.TextField(verbose_name='课程简介')
    detail = UEditorField(verbose_name='课程详情',
                          width=700,
                          height=400,
                          toolbars='full',
                          imagePath='ueditor/images/',
                          filePath='ueditor/files/',
                          upload_settings={'imageMaxSizing': 1024000},
                          default='')
    category = models.CharField(choices=(('qd', '前端开发'), ('hd', '后端开发')),
                                verbose_name='课程类型', max_length=5)
    course_notice = models.CharField(max_length=50, verbose_name='课程公告',
                                     null=True, blank=True)
    course_need = models.CharField(max_length=100, verbose_name='课程须知',
                                   null=True, blank=True)
    teacher_tell = models.CharField(max_length=100, verbose_name='讲师提醒',
                                    null=True, blank=True)
    org_info = models.ForeignKey(OrgInfo, verbose_name='所属机构',
                                 on_delete=models.CASCADE)
    teacher_Info = models.ForeignKey(TeacherInfo, verbose_name='讲师',
                                     on_delete=models.CASCADE)
    is_banner = models.BooleanField(default=False,
                                    verbose_name='是否轮播')
    add_time = models.DateTimeField(default=datetime.now, verbose_name='添加时间')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural = verbose_name = '课程信息'


class LessonInfo(models.Model):
    name = models.CharField(max_length=50, verbose_name='章节名')
    course_info = models.ForeignKey(CourseInfo, verbose_name='所属课程',
                                    on_delete=models.CASCADE)
    add_time = models.DateTimeField(default=datetime.now, verbose_name='添加时间')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural = verbose_name = '章节信息'


class VideoInfo(models.Model):
    name = models.CharField(max_length=50, verbose_name='视频名称')
    study_time = models.IntegerField(default=0, verbose_name='视频时长')
    url = models.URLField(default='http://www.atguigu.com', verbose_name='视频链接', max_length=200)
    add_time = models.DateTimeField(default=datetime.now, verbose_name='添加时间')
    lesson_info = models.ForeignKey(LessonInfo, verbose_name='所属章节',
                                    on_delete=models.CASCADE)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural = verbose_name = '视频信息'


class SourceInfo(models.Model):
    name = models.CharField(max_length=50, verbose_name='资源名称')
    download = models.FileField(upload_to='source/', verbose_name='资源链接', max_length=200)
    course_info = models.ForeignKey(CourseInfo, verbose_name='所属课程',
                                    on_delete=models.CASCADE)
    add_time = models.DateTimeField(default=datetime.now, verbose_name='添加时间')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural = verbose_name = '资源信息'

apps/users/models.py
from datetime import datetime

from django.db import models
from django.contrib.auth.models import AbstractUser


# Create your models here.
class UserProfile(AbstractUser):
    image = models.ImageField(upload_to='user/', max_length=200, verbose_name='用户头像',
                              null=True, blank=True)

    nick_name = models.CharField(max_length=20, verbose_name='用户昵称',
                                 null=True, blank=True)

    birthday = models.DateField(verbose_name='用户生日',
                                    null=True, blank=True)

    gender = models.CharField(choices=(('girl', '女'), ('boy', '男')), max_length=10, verbose_name='性别',
                              default='girl')

    address = models.CharField(max_length=100, verbose_name='用户地址',
                               null=True, blank=True)

    phone = models.CharField(max_length=11, verbose_name='用户手机',
                             null=True, blank=True)
    is_start = models.BooleanField(default=False, verbose_name='是否激活')
    add_time = models.DateTimeField(default=datetime.now, verbose_name='添加时间')

    def __str__(self):
        return self.username

    def get_msg_counter(self):
        from operations.models import UserMessage
        counter = UserMessage.objects.filter(message_man=self.id, message_status=False).count()
        return counter

    class Meta:
        verbose_name = verbose_name_plural = '用户信息'


class BannerInfo(models.Model):
    image = models.ImageField(upload_to='banner/', verbose_name='轮播图', max_length=200)

    url = models.URLField(default='http://www.atguigu.com', verbose_name='图片链接', max_length=200)

    add_time = models.DateTimeField(default=datetime.now, verbose_name='添加时间')

    def __str__(self):
        return str(self.image)

    class Meta:
        verbose_name_plural = verbose_name = '轮播图'


class EmailVerifyCode(models.Model):
    code = models.CharField(max_length=50, verbose_name='邮箱验证码')

    email = models.EmailField(max_length=200, verbose_name='验证码邮箱')

    send_type = models.IntegerField(choices=((1, 'register'), (2, 'forget'), (3, 'change')), verbose_name='验证类型')

    add_time = models.DateTimeField(default=datetime.now,  verbose_name='添加时间')

    def __str__(self):
        return str(self.code)

    class Meta:
        verbose_name_plural = verbose_name = '邮箱验证码'

apps/users/forms.py
from django import forms
from captcha.fields import CaptchaField
from .models import UserProfile, EmailVerifyCode


class UserRegisterForm(forms.Form):
    # 邮箱格式验证
    email = forms.EmailField(required=True)
    # 密码格式验证
    password = forms.CharField(required=True, min_length=3, max_length=15,
                               error_messages={
                                   'required': '密码必须填写',
                                   'min_length': '密码至少三位',
                                   'max_length': '密码不能超过15位'
                               })
    # 验证码
    captcha = CaptchaField()


class UserLoginForm(forms.Form):
    # 邮箱格式验证
    email = forms.EmailField(required=True)
    # 密码格式验证
    password = forms.CharField(required=True, min_length=3, max_length=15,
                               error_messages={
                                   'required': '密码必须填写',
                                   'min_length': '密码至少三位',
                                   'max_length': '密码不能超过15位'
                               })


class UserForgetForm(forms.Form):
    # 邮箱格式验证
    email = forms.EmailField(required=True)
    # 验证码
    captcha = CaptchaField()


class UserResetForm(forms.Form):
    password1 = forms.CharField(required=True, min_length=3, max_length=15,
                                error_messages={
                                    'required': '密码必须填写',
                                    'min_length': '密码至少三位',
                                    'max_length': '密码不能超过15位'
                                })
    password2 = forms.CharField(required=True, min_length=3, max_length=15,
                                error_messages={
                                    'required': '密码必须填写',
                                    'min_length': '密码至少三位',
                                    'max_length': '密码不能超过15位'
                                })


class UserChangeImageForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ['image']


class UserChangeInfoForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ['nick_name', 'gender', 'address', 'phone', 'birthday']


class UserChangeEmailForm(forms.ModelForm):
    class Meta:
        model = EmailVerifyCode
        fields = ['email']


class UserResetEmailForm(forms.ModelForm):
    class Meta:
        model = EmailVerifyCode
        fields = ['email', 'code']


class UserPwdForm(forms.Form):
    pwd = forms.CharField(required=True, min_length=3, max_length=15,
                          error_messages={
                              'required': '密码必须填写',
                              'min_length': '密码至少三位',
                              'max_length': '密码不能超过15位'
                          })
    repwd = forms.CharField(required=True, min_length=3, max_length=15,
                            error_messages={
                                'required': '密码必须填写',
                                'min_length': '密码至少三位',
                                'max_length': '密码不能超过15位'
                            })

templates/users/usercenter-base.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block css %}
    <link rel="stylesheet" type="text/css" href="{% static 'js/plugins/queryCity/css/cityLayout.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/lq.datetimepick.css' %}"/>
    {% block mycss %}

    {% endblock %}
{% endblock %}
{% block middle %}
    <div class="middle">
        <div class="wp">
            <a href="/"><img class="fl" src="{% static 'images/logo1.png' %}"/></a>
            <h1>我的谷粒教育网</h1>
        </div>
    </div>
{% endblock %}
{% block content %}
    <section>
        <div class="wp">
            <ul class="crumbs">
                <li><a href="/">首页</a>></li>
                <li><a href="/users/user_info">个人中心</a>></li>
                <li>{% block breach %}{% endblock %}</li>
            </ul>
        </div>
    </section>
    <section>
        <div class="wp list personal_list">
            <div class="left">
                <ul>
                    <li {% if request.path|slice:'7:16' == 'user_info' %}class="active2"{% endif %}><a href="{% url 'users:user_info' %}">个人资料</a></li>
                    <li {% if request.path|slice:'7:18' == 'user_course' %}class="active2"{% endif %}><a href="{% url 'users:user_course' %}">我的课程</a></li>
                    <li {% if request.path|slice:'7:19' == 'user_fav_org' %}class="active2"{% endif %}><a href="{% url 'users:user_fav_org' %}">我的收藏</a></li>
                    <li>
                        <a href="{% url 'users:user_message' %}" style="position: relative;">
                            我的消息
                        </a>
                    </li>
                </ul>
            </div>
            {% block right %}{% endblock %}
        </div>
    </section>
    {% block dialog %}
        <div class="dialog" id="jsDialog">
            <div class="resetpwdbox dialogbox" id="jsResetDialog">
                <h1>修改密码</h1>
                <div class="close jsCloseDialog"><img src="{% static 'images/dig_close.png' %}"/></div>
                <div class="cont">
                    <form id="jsResetPwdForm" autocomplete="off">
                        <div class="box">
                            <span class="word2">新&nbsp;&nbsp;密&nbsp;&nbsp;码</span>
                            <input type="password" id="pwd" name="password1" placeholder="6-20位非中文字符"/>
                        </div>
                        <div class="box">
                            <span class="word2">确定密码</span>
                            <input type="password" id="repwd" name="password2" placeholder="6-20位非中文字符"/>
                        </div>
                        <div class="error btns" id="jsResetPwdTips"></div>
                        <div class="button">
                            <input id="jsResetPwdBtn1" type="button" value="提交"/>
                        </div>
                    </form>
                </div>
            </div>
            <div class="dialogbox changeemai1 changephone" id="jsChangeEmailDialog">
                <h1>修改邮箱</h1>
                <div class="close jsCloseDialog"><img src="{% static 'images/dig_close.png' %}"/></div>
                <p>请输入新的邮箱地址</p>
                <form id="jsChangeEmailForm" autocomplete="off">
                    {% csrf_token %}
                    <div class="box">
                        <input class="fl change_email" name="email" id="jsChangeEmail" type="text"
                               placeholder="输入重新绑定的邮箱地址">
                    </div>
                    <div class="box">
                        <input class="fl email_code" type="text" id="jsChangeEmailCode" name="code"
                               placeholder="输入邮箱验证码">
                        <input class="getcode getting" type="button" id="jsChangeEmailCodeBtn1" value="获取验证码">
                    </div>
                    <div class="error btns change_email_tips" id="jsChangeEmailTips">请输入...</div>
                    <div class="button">
                        <input class="changeemai_btn" id="jsChangeEmailBtn1" type="button" value="完成"/>
                    </div>
                    </form>
            </div>
        </div>
        <div class="bg" id="dialogBg"></div>
    {% endblock %}
{% endblock %}
{% block footer %}{% endblock %}
{% block js %}
    <script src='{% static 'js/plugins/jquery.upload.js' %}' type='text/javascript'></script>
    <script src="{% static 'js/validate.js' %}" type="text/javascript"></script>
    {% block user %}
    <script src="{% static 'js/deco-user.js' %}"></script>
    {% endblock %}
    <script>
        $(function () {
            $("#jsChangeEmailCodeBtn1").click(function () {
                let email = $("#jsChangeEmail").val();
                $.ajax({
                    type: "POST",
                    url: "{% url 'users:user_changeemail' %}",
                    data: {
                        "email": email,
                        "csrfmiddlewaretoken": "{{ csrf_token }}"
                    },
                    success:function (callback) {
                        if(callback.status == 'ok'){
                            alert(callback.msg)
                        }else{

                            alert(callback.msg)
                        }
                    }
                })
            })
            $("#jsChangeEmailBtn1").click(function () {
                let email = $("#jsChangeEmail").val();
                let code = $("#jsChangeEmailCode").val();
                $.ajax({
                    type: "POST",
                    url: "{% url 'users:user_resetemail' %}",
                    data: {
                        "email": email,
                        "code": code,
                        "csrfmiddlewaretoken": "{{ csrf_token }}"
                    },
                    success:function (callback) {
                        if(callback.status == 'ok'){
                            alert(callback.msg);
                            window.location.href = "{% url 'users:user_login' %}";
                        }else{
                            alert(callback.msg);
                        }
                    }
                })
            })
            $("#jsResetPwdBtn1").click(function () {
                let pwd = $("#pwd").val();
                let repwd = $("#repwd").val();
                $.ajax({
                    type: "POST",
                    url: "{% url 'users:user_change_pwd' %}",
                    data: {
                        "pwd": pwd,
                        "repwd": repwd,
                        "csrfmiddlewaretoken": "{{ csrf_token }}"
                    },
                    success:function (callback) {
                        if (callback.status == "ok"){
                            window.location.href = "{% url 'users:user_login' %}";
                        }else {
                            alert(callback.msg);
                        }
                    }
                })
            })
        })
    </script>
    {% block myjs %}{% endblock %}
{% endblock %}

templates/users/usercenter-fav-course.html
{% extends 'users/usercenter-base.html' %}
{% block title %}
    我的收藏- 谷粒教育网
{% endblock %}
{% block breach %}
    我的收藏
{% endblock %}
{% block right %}
    <div class="right">
        <div class="personal_des Releasecont">
            <div class="head">
                <h1>我的收藏</h1>
            </div>
        </div>
        <div class="personal_des permessage">
            <div class="head">
                <ul class="tab_header messagehead">
                    <li><a href="{% url 'users:user_fav_org' %}">课程机构</a></li>
                    <li><a href="{% url 'users:user_fav_teacher' %}">授课教师 </a></li>
                    <li class="active"><a href="{% url 'users:user_fav_course' %}">公开课程</a></li>
                </ul>
            </div>
            <div class="companycenter">
                <div class="group_list brief">
                    {% for course in course_list %}
                        <div class="module1_5 box">
                            <a href="{% url 'courses:course_detail' course.id %}">
                                <img width="214" height="190" src="/media/{{ course.image }}"/>
                            </a>
                            <div class="des">
                                <a href="{% url 'courses:course_detail' course.id %}"><h2>{{ course.name }}</h2></a>
                                <span class="fl">时长：<i class="key">{{ course.study_time }}</i></span>
                                <span class="fr">学习人数：{{ course.study_num }}</span>
                            </div>
                            <div class="bottom">
                                <span class="fl">{{ course.org_info.name }}</span>
                                <span class="delete-group fr jsDeleteFav_course" data-favid="{{ course.id }}"></span>
                            </div>
                        </div>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
{% endblock %}
{% block myjs %}
    {% block user %}

    {% endblock %}
<script>
        $(function () {
            $(".delete-group").click(function () {
                {# prop()用来取元素自带的属性值或者设置值，attr用来取元素自定义的属性值或设置值 #}
                let fav_id = $(this).attr("data-favid");
                let fav_type = 2;
                let obj = $(this);
                $.ajax({
                    type: "GET",
                    url: "{% url 'operations:user_delete_love' %}",
                    data: {
                        "love_id": fav_id,
                        "love_type": fav_type
                    },
                    success:function (callback) {
                        if(callback.status == 'ok'){
                            obj.parents(".module1_5").remove()
                        }else{
                            alert(callback.msg);
                        }
                    }
                })
            })
        })
    </script>
{% endblock %}

templates/users/usercenter-fav-org.html
{% extends 'users/usercenter-base.html' %}
{% load staticfiles %}
{% block title %}
    我的收藏- 谷粒教育网
{% endblock %}
{% block breach %}
    我的收藏
{% endblock %}
{% block right %}
    <div class="right">
        <div class="personal_des Releasecont">
            <div class="head">
                <h1>我的收藏</h1>
            </div>

        </div>
        <div class="personal_des permessage">
            <div class="head">
                <ul class="tab_header messagehead">
                    <li class="active"><a href="{% url 'users:user_fav_org' %}">课程机构</a></li>
                    <li><a href="{% url 'users:user_fav_teacher' %}">授课教师 </a></li>
                    <li><a href="{% url 'users:user_fav_course' %}">公开课程</a></li>
                </ul>
            </div>
            <div class="messagelist">

                <div class="messages butler_list company company-fav-box">
                    {% for org in org_list %}
                        <dl class="des fr">
                            <dt>
                                <a href="{% url 'orgs:org_detail' org.id %}">
                                    <img width="160" height="90" src="/media/{{ org.image }}"/>
                                </a>
                            </dt>
                            <dd>
                                <h1><a href="{% url 'orgs:org_detail' org.id %}">{{ org.name }}</a></h1>
                                <div class="pic fl" style="width:auto;">
                                    <img src="{% static 'images/authentication.png' %}"/>

                                    <img src="{% static 'images/gold.png' %}"/>

                                </div>
                                <span class="c8 clear">{{ org.city_info.name }}</span>
                                <div class="delete jsDeleteFav_org" data-favid="{{ org.id }}"></div>
                            </dd>
                        </dl>
                    {% endfor %}
                </div>

            </div>
        </div>
    </div>
{% endblock %}
{% block myjs %}
    {% block user %}

    {% endblock %}
    <script>
        $(function () {
            $(".delete").click(function () {
                {# prop()用来取元素自带的属性值或者设置值，attr用来取元素自定义的属性值或设置值 #}
                let fav_id = $(this).attr("data-favid");
                let fav_type = 1;
                let obj = $(this);
                $.ajax({
                    type: "GET",
                    url: "{% url 'operations:user_delete_love' %}",
                    data: {
                        "love_id": fav_id,
                        "love_type": fav_type
                    },
                    success:function (callback) {
                        if(callback.status == 'ok'){
                            obj.parents(".des").remove()
                        }else{
                            alert(callback.msg);
                        }
                    }
                })
            })
        })
    </script>
{% endblock %}

templates/users/usercenter-fav-teacher.html
{% extends 'users/usercenter-base.html' %}
{% load staticfiles %}
{% block title %}
    我的收藏- 谷粒教育网
{% endblock %}
{% block breach %}
    我的收藏
{% endblock %}
{% block right %}
    <div class="right">
        <div class="personal_des Releasecont">
            <div class="head">
                <h1>我的收藏</h1>
            </div>
        </div>
        <div class="personal_des permessage">
            <div class="head">
                <ul class="tab_header messagehead">
                    <li><a href="{% url 'users:user_fav_org' %}">课程机构</a></li>
                    <li class="active"><a href="{% url 'users:user_fav_teacher' %}">授课教师 </a></li>
                    <li><a href="{% url 'users:user_fav_course' %}">公开课程</a></li>
                </ul>
            </div>
            <div class="messagelist">
                {% for teacher in teacher_list %}
                    <div class=" butler_list butler-fav-box">
                        <dl class="des users">
                            <dt>
                                <a href="{% url 'orgs:teacher_detail' teacher.id %}">
                                    <img width="100" height="100" src="/media/{{ teacher.image }}"/>
                                </a>
                            </dt>
                            <dd>
                                <h1>
                                    <a href="{% url 'orgs:teacher_detail' teacher.id %}">
                                        {{ teacher.name }}<span class="key">认证教师</span>
                                    </a>
                                </h1>
                                <ul class="cont clearfix">
                                    <li class="time">工作年限：<span>{{ teacher.work_year }}年</span></li>
                                    <li class="c7">课程数：<span>{{ teacher.courseinfo_set.count }}</span></li>
                                </ul>
                                <ul class="cont clearfix">
                                    <li class="time">工作公司：<span>{{ teacher.work_company }}</span></li>
                                    <li class="c7">公司职位：<span>{{ teacher.work_position }}</span></li>
                                </ul>
                            </dd>
                            <div class="delete jsDeleteFav_teacher" data-favid="{{ teacher.id }}"></div>
                        </dl>
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>
{% endblock %}
{% block myjs %}
    <script>
        $(function () {
            $(".delete").click(function () {
                {# prop()用来取元素自带的属性值或者设置值，attr用来取元素自定义的属性值或设置值 #}
                let fav_id = $(this).attr("data-favid");
                let fav_type = 3;
                let obj = $(this);
                $.ajax({
                    type: "GET",
                    url: "{% url 'operations:user_delete_love' %}",
                    data: {
                        "love_id": fav_id,
                        "love_type": fav_type
                    },
                    success: function (callback) {
                        if (callback.status == 'ok') {
                            obj.parents(".des").remove()
                        } else {
                            alert(callback.msg);
                        }
                    }
                })
            })
        })
    </script>
    {% block user %}

    {% endblock %}
{% endblock %}